const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const GenerateDoc = (data, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      console.log("🛠️ Starting PDF generation...");

      if (!outputPath) throw new Error("Missing output path");
      if (!data) throw new Error("No data passed to GenerateDoc");

      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(outputPath);

      stream.on("finish", () => {
        console.log("✅ PDF write complete:", outputPath);
        resolve(outputPath);
      });

      stream.on("error", (err) => {
        console.error("❌ Stream error while writing PDF:", err);
        reject(err);
      });

      doc.pipe(stream);

      // --- Header ---
      doc
        .fontSize(22)
        .fillColor("#1F2937")
        .text(" Job Application Invoice", { align: "center", underline: true });

      doc.moveDown();
      doc
        .fontSize(10)
        .fillColor("gray")
        .text(`Generated on: ${new Date().toLocaleDateString()}`, { align: "right" });
      doc.moveDown(1.5);

      // --- Applicant Info Section ---
      doc
        .fontSize(12)
        .fillColor("#000")
        .text("Applicant Information", { underline: true });
      doc.moveDown(0.5);

      const addField = (label, value) => {
        doc
          .font("Helvetica-Bold")
          .text(`${label}: `, { continued: true })
          .font("Helvetica")
          .text(value || "N/A");
      };

      addField("Full Name", `${data.firstName || ""} ${data.lastName || ""}`);
      addField("Email", data.email);
      addField("Phone", data.phone);
      addField("Position Applied", data.position);
      addField("Expected Salary", data.expectedSalary);
      addField("Availability", data.availability);
      addField("Years of Experience", data.experience);

      // --- Cover Letter ---
      doc.moveDown();
      doc
        .font("Helvetica-Bold")
        .fontSize(12)
        .text("Cover Letter", { underline: true });
      doc.moveDown(0.5);
      doc
        .font("Helvetica")
        .fontSize(11)
        .fillColor("#111")
        .text(data.coverLetter || "N/A", {
          width: 500,
          lineGap: 4,
          align: "justify",
        });

      // --- Footer ---
      doc.moveDown(2);
      doc
        .fontSize(10)
        .fillColor("gray")
        .text("Generated by YourCompany HR System", {
          align: "center",
          opacity: 0.7,
        });

      doc.end();
      console.log("📄 doc.end() called");
    } catch (err) {
      console.error("❌ Outer error in GenerateDoc:", err);
      reject(err);
    }
  });
};


module.exports = GenerateDoc;
